In [1]:
# Load the CSV file
base = '../../../../rcie-system-metrics-data/'
domain = '2023-06-12_11-33-10_rcie-api-default/'
file = 'metrics-with-output-and-standardized-unit.csv'
file_path = base + domain + file

In [2]:
# Load libraries
import pandas as pd
import pickle

In [3]:
col_names = ["time","timestamp","cpu_usage","memory_usage","bandwidth_inbound","bandwidth_outbound","tps","tps_error","response_time","status"]

# Load dataset
df = pd.read_csv(file_path, skiprows=1, header=None, names=col_names)
df.head()

,time,timestamp,cpu_usage,memory_usage,bandwidth_inbound,bandwidth_outbound,tps,tps_error,response_time,status
0,2023-06-12 11:33:10,1686544390000,0.006,0.374,8.73,6.42,0.2,0.0,15.1,0
1,2023-06-12 11:33:15,1686544395000,0.012,0.374,8.79,6.49,0.2,0.0,20.1,0
2,2023-06-12 11:33:20,1686544400000,0.008,0.374,8.77,6.46,0.2,0.0,14.3,0
3,2023-06-12 11:33:25,1686544405000,0.008,0.374,8.74,6.44,0.2,0.0,18.9,0
4,2023-06-12 11:33:30,1686544410000,0.008,0.374,8.88,6.53,0.2,0.0,17.5,0

In [4]:
# Split dataset in features and target variable
feature_cols = ["cpu_usage","memory_usage","bandwidth_inbound","bandwidth_outbound","tps","response_time"]
feature_cols_with_timestamp = ["timestamp","cpu_usage","memory_usage","bandwidth_inbound","bandwidth_outbound","tps","response_time"]
features = df[feature_cols] 
features_with_timestamp = df[feature_cols_with_timestamp]

In [5]:
# Share the data
pickle.dump(df, open("./common/df.p", "wb"))
pickle.dump(features, open("./common/features.p", "wb"))
pickle.dump(features_with_timestamp, open("./common/features_with_timestamp.p", "wb"))

pickle.dump(feature_cols, open("./common/feature_cols.p", "wb"))
pickle.dump(feature_cols_with_timestamp, open("./common/feature_cols_with_timestamp.p", "wb"))